pipeline {
    agent any
   
    stages {
        stage('build') {
            steps {
                sh """
                    docker build -t ecommercedepi .
                """
            }
        }

        stage('push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'marwantoken', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker tag ecommercedepi $DOCKER_USER/ecommercedepi:latest
                        docker push $DOCKER_USER/ecommercedepi:latest
                    """
                }
            }
        }

    }
}
